module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "blob-green": "var(--blob-green)",
        "blue-600": "var(--blue-600)",
        "textweaker-text": "var(--textweaker-text)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        teal: {
          50: "#f3fafb",
          100: "#d9f1f5",
          200: "#b3e3eb",
          300: "#82cfdd",
          400: "#4db4c9",
          500: "#266c92",
          600: "#0e5371",
          700: "#0a405a",
          800: "#082f44",
          900: "#05202e",
        },
      },
      fontFamily: {
        "font-100-12px-regular": "var(--font-100-12px-regular-font-family)",
        "font-200-14px-light": "var(--font-200-14px-light-font-family)",
        "font-200-14px-medium": "var(--font-200-14px-medium-font-family)",
        "font-200-14px-regular": "var(--font-200-14px-regular-font-family)",
        "font-200-14px-semibold": "var(--font-200-14px-semibold-font-family)",
        "font-300-16px-regular": "var(--font-300-16px-regular-font-family)",
        "font-400-18px-medium": "var(--font-400-18px-medium-font-family)",
        "font-400-18px-semibold": "var(--font-400-18px-semibold-font-family)",
        "font-50-11px-semibold": "var(--font-50-11px-semibold-font-family)",
        "font-500-24px-medium": "var(--font-500-24px-medium-font-family)",
        "label-default": "var(--label-default-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "shadow-100": "var(--shadow-100)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
